# Project information
site_name: Material for MkDocs
site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Martin Donath
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: squidfunk/mkdocs-material
repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2023 Martin Donath

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    # - search.suggest
    # - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  # language: en
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline 
  #       name: Switch to dark mode
  #     primary: teal
  #     accent: purple 
  #   - scheme: slate 
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode    
  #     primary: teal
  #     accent: lime
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - social
  - search
  - offline

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/doosan-maverick
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/doosan-maverick
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/doosan-maverick/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/doosan-maverick"  target="_blank" rel="noopener">Doosan Pagooah</a>